# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190712_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(default='', max_length=50, verbose_name='图标'),
            preserve_default=False,
        ),
    ]
