# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_is_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(default='', max_length=32, verbose_name='图标'),
            preserve_default=False,
        ),
    ]
